[project]
name = "xoxcharts"
version = "2024-06-04"
description = ""
dependencies = [
    "flask",
    "pandas",
    "numpy",
    "wtforms"
    ]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"